/**
 * Platt/logistic calibration for the neural score. GENERATED by bench/calibrate.mjs — do not
 * hand-edit. Fitted on the internal public benchmark train split only.
 */
export const CALIBRATION = Object.freeze({
  enabled: true,
  a: 0.5204275499101693,
  b: 2.9321089913761167,
  fittedOn: 'haywoodsloan-int8__full-raw.jsonl',
  trainSize: 235,
  testBalancedAccuracyBefore: 0.80688088283025,
  testBalancedAccuracyAfter: 0.837796170074651,
});
