/**
 * Platt/logistic calibration for the neural score. GENERATED by bench/calibrate.mjs — do not
 * hand-edit. Fitted on the internal public benchmark train split only.
 */
export const CALIBRATION = Object.freeze({
  enabled: true,
  a: 1.0398150338581258,
  b: 0.04050349671002348,
  fittedOn: 'haywoodsloan-int8__pipeline-raw.jsonl',
  trainSize: 235,
  testBalancedAccuracyBefore: 0.8313859136643946,
  testBalancedAccuracyAfter: 0.8281402142161636,
  eceBefore: 0.1960040829440803,
  eceAfter: 0.21925853319732908,
});
