/**
 * Platt/logistic calibration for the neural score. GENERATED by bench/calibrate.mjs — do not
 * hand-edit. Fitted on the internal public benchmark train split only.
 */
export const CALIBRATION = Object.freeze({
  enabled: true,
  a: 0.5119546598871559,
  b: 3.0046474333262188,
  fittedOn: 'haywoodsloan-int8__single-full.jsonl',
  trainSize: 235,
  testBalancedAccuracyBefore: 0.80688088283025,
  testBalancedAccuracyAfter: 0.8281402142161636,
  eceBefore: 0.24415134354455686,
  eceAfter: 0.058657835134065944,
});
