/**
 * Fit Platt (logistic) calibration for the neural score on the benchmark TRAIN split, and write
 * src/shared/fusion/calibration.js. Uses only public benchmark data — never the maintainers' set.
 *
 * Method: 1-D logistic regression on logit(score) -> label, via gradient descent. The bounty
 * operating point is 0.65; after fitting we verify the balanced accuracy at that threshold and
 * report the achieved margin.
 *
 * Usage: node bench/calibrate.mjs --results bench/results/<file>.jsonl [--split-seed 1337]
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { seededShuffle } from '../src/shared/rng.js';
import { balancedAccuracyWithCi } from '../src/shared/metrics.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_PATH = path.join(repoRoot, 'src', 'shared', 'fusion', 'calibration.js');

function parseArgs(argv) {
  const args = { results: null, 'split-seed': 1337, threshold: 0.65 };
  for (let i = 2; i < argv.length; i++) {
    const token = argv[i].replace(/^--/, '');
    const eq = token.indexOf('=');
    const key = eq >= 0 ? token.slice(0, eq) : token;
    const value = eq >= 0 ? token.slice(eq + 1) : argv[++i];
    if (key in args) args[key] = ['split-seed', 'threshold'].includes(key) ? Number(value) : value;
  }
  if (!args.results) throw new Error('--results <file.jsonl> is required');
  return args;
}

const clamp01 = (x) => Math.min(1, Math.max(0, x));
const logit = (p) => Math.log((clamp01(p) + 1e-9) / (1 - clamp01(p) + 1e-9));
const sigmoid = (x) => 1 / (1 + Math.exp(-x));

/** Logistic regression on logit(score) -> label(1=fake). Returns { a, b }. */
function fitLogistic(samples, { epochs = 2000, lr = 0.1, l2 = 1e-3 } = {}) {
  let a = 1;
  let b = 0;
  const xs = samples.map((s) => logit(s.score));
  const ys = samples.map((s) => (s.label === 'fake' ? 1 : 0));
  for (let epoch = 0; epoch < epochs; epoch++) {
    let ga = 0;
    let gb = 0;
    for (let i = 0; i < xs.length; i++) {
      const p = sigmoid(a * xs[i] + b);
      const err = p - ys[i];
      ga += err * xs[i];
      gb += err;
    }
    ga = ga / xs.length + l2 * a;
    gb = gb / xs.length;
    a -= lr * ga;
    b -= lr * gb;
  }
  return { a, b };
}

async function main() {
  const args = parseArgs(process.argv);
  const text = await readFile(
    path.isAbsolute(args.results) ? args.results : path.join(repoRoot, args.results),
    'utf8',
  );
  const all = text
    .split('\n')
    .filter(Boolean)
    .map(JSON.parse)
    .filter((r) => r.score != null && !r.error && !r.augmented);

  // Stratified 50/50 train/test split.
  const fakes = seededShuffle(
    all.filter((r) => r.label === 'fake'),
    args['split-seed'],
  );
  const reals = seededShuffle(
    all.filter((r) => r.label === 'real'),
    args['split-seed'] + 1,
  );
  const train = [
    ...fakes.slice(0, Math.floor(fakes.length / 2)),
    ...reals.slice(0, Math.floor(reals.length / 2)),
  ];
  const test = [
    ...fakes.slice(Math.floor(fakes.length / 2)),
    ...reals.slice(Math.floor(reals.length / 2)),
  ];

  const { a, b } = fitLogistic(train);

  // Evaluate calibrated scores on the held-out test split.
  const calibratedTest = test.map((r) => ({ ...r, score: sigmoid(a * logit(r.score) + b) }));
  const before = balancedAccuracyWithCi(test, args.threshold);
  const after = balancedAccuracyWithCi(calibratedTest, args.threshold);

  console.log(`[calibrate] train=${train.length} test=${test.length}`);
  console.log(`[calibrate] fitted a=${a.toFixed(4)} b=${b.toFixed(4)}`);
  console.log(
    `[calibrate] test BA @ ${args.threshold}: before=${(before.balancedAccuracy * 100).toFixed(2)}%  after=${(after.balancedAccuracy * 100).toFixed(2)}%`,
  );

  const out = `/**
 * Platt/logistic calibration for the neural score. GENERATED by bench/calibrate.mjs — do not
 * hand-edit. Fitted on the internal public benchmark train split only.
 */
export const CALIBRATION = Object.freeze({
  enabled: true,
  a: ${a},
  b: ${b},
  fittedOn: '${path.basename(args.results)}',
  trainSize: ${train.length},
  testBalancedAccuracyBefore: ${before.balancedAccuracy},
  testBalancedAccuracyAfter: ${after.balancedAccuracy},
});
`;
  await writeFile(OUT_PATH, out, 'utf8');
  console.log(`[calibrate] wrote ${path.relative(repoRoot, OUT_PATH)}`);
  if (after.balancedAccuracy < before.balancedAccuracy) {
    console.warn('[calibrate] WARNING: calibration reduced test BA — consider disabling.');
  }
}

main().catch((err) => {
  console.error('[calibrate] FAILED:', err);
  process.exitCode = 1;
});
